dist: precise

language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - hhvm

sudo: false

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

cache:
  - apt

addons:
  apt:
    packages:
      - nginx
      - realpath
  hosts:
    - vanilla.test

install:
  - composer self-update
  - composer install -o
  - composer require phpunit/phpunit ~5
  - tests/travis/setup.sh

script:
  - tests/travis/php-lint.sh ./applications
  - tests/travis/php-lint.sh ./conf
  - tests/travis/php-lint.sh ./library
  - tests/travis/php-lint.sh ./plugins
  - tests/travis/php-lint.sh ./themes
  - ./vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage.clover
  - ls -lah ./conf
  - cat /tmp/error.log
  - cat /tmp/access.log

notifications:
  hipchat:
    format: html
    on_success: change
    rooms:
      - secure: "SsKmSAZFynBz4ZKm5NPyuXvNjIMyxpNMXsgfXVImG8xjQHdXjEpZAiyckK8E2lXBBypv59Oex6wsS0RvyxpI/mwQ9dTQ9ayurQxwH3V5Q/+pRbtXJOkP+DSIsHhRb9D4xa5nPbh4N48+QZvUFiH2ety9/gev4mtMkLv3lC0vgpc="
    template:
      - '%{repository_slug} build <a href="%{build_url}">#%{build_number}</a> (%{branch} - <a href="%{compare_url}">%{commit}</a> by %{author}): %{message}'
